version: 2
project_name: ipaddr
before:
  hooks:
    - go mod download
builds:
  -
    env:
      - CGO_ENABLED=0
    binary: ipaddr
    flags:
      - -trimpath
    ldflags:
      - -w -s
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    format_overrides:
      - goos: windows
        formats: zip
      - goos: darwin
        formats: zip
    files:
      - UNLICENSE
      - README.MD
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
signs:
  - artifacts: checksum
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^release:'
source:
  enabled: true
  name_template: "{{ .ProjectName }}_source"
  format: "tar.gz"
